
package Telas;
import Controle.ControlaDicionario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import entidade.Termo;

public class TelaPrincipal extends javax.swing.JFrame {
    String exibeTermo;
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(TelaPrincipal.MAXIMIZED_BOTH);
        this.pesquisar();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdExibeDados = new javax.swing.JDialog();
        jpTras = new javax.swing.JPanel();
        jlExibeTermo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtpSignificado = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtpFonte = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jpCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpInferir = new javax.swing.JPanel();
        jtfPesquisa = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jlbPesquisarPor = new javax.swing.JLabel();
        jpSuperior = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jpEsquerda = new javax.swing.JPanel();
        jlNumero = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jlTermo = new javax.swing.JLabel();
        jlSignificado = new javax.swing.JLabel();
        jlbFonte = new javax.swing.JLabel();
        jtfFonte = new javax.swing.JTextField();
        jtfTermo = new javax.swing.JTextField();
        jtfSignificado = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jpDireita = new javax.swing.JPanel();
        jbSair = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbExibir = new javax.swing.JButton();

        jdExibeDados.setTitle("Exibir dados do termo selecionado");
        jdExibeDados.setType(java.awt.Window.Type.POPUP);
        jdExibeDados.getContentPane().setLayout(new javax.swing.BoxLayout(jdExibeDados.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        jdExibeDados.setResizable(true);
        jdExibeDados.setSize(600, 350);
        jdExibeDados.setLocationRelativeTo(null);
        jdExibeDados.setModal(true);

        jpTras.setBackground(new java.awt.Color(255, 255, 255));
        jpTras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 91, 147)));

        jlExibeTermo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jlExibeTermo.setForeground(new java.awt.Color(33, 91, 147));
        jlExibeTermo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExibeTermo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Termo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(33, 91, 147))); // NOI18N
        jlExibeTermo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtpSignificado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Significado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(33, 91, 147))); // NOI18N
        jtpSignificado.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jtpSignificado);
        jtpSignificado.setEditable(false);

        jtpFonte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fonte", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(33, 91, 147))); // NOI18N
        jtpFonte.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(jtpFonte);
        jtpFonte.setEditable(false);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTrasLayout = new javax.swing.GroupLayout(jpTras);
        jpTras.setLayout(jpTrasLayout);
        jpTrasLayout.setHorizontalGroup(
            jpTrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jlExibeTermo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTrasLayout.createSequentialGroup()
                        .addGap(0, 523, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jpTrasLayout.setVerticalGroup(
            jpTrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlExibeTermo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdExibeDados.getContentPane().add(jpTras);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCentral.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 91, 147), 1, true), "Termos cadastrados:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(33, 91, 147))); // NOI18N
        jpCentral.setPreferredSize(new java.awt.Dimension(400, 400));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Termo", "Significado", "Fonte"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jpCentralLayout = new javax.swing.GroupLayout(jpCentral);
        jpCentral.setLayout(jpCentralLayout);
        jpCentralLayout.setHorizontalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpCentralLayout.setVerticalGroup(
            jpCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCentralLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        getContentPane().add(jpCentral, java.awt.BorderLayout.CENTER);

        jpInferir.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 91, 147)), "Área de pesquisa:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(33, 91, 147))); // NOI18N

        jtfPesquisa.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jbPesquisar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbPesquisar.setText("Pesquisar / Listar");
        jbPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jlbPesquisarPor.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jlbPesquisarPor.setText("Pesquisar por numero, termo, significado ou fonte:");
        jlbPesquisarPor.setToolTipText("");
        jlbPesquisarPor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlbPesquisarPor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlbPesquisarPor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jpInferirLayout = new javax.swing.GroupLayout(jpInferir);
        jpInferir.setLayout(jpInferirLayout);
        jpInferirLayout.setHorizontalGroup(
            jpInferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInferirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbPesquisar)
                .addGroup(jpInferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInferirLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jlbPesquisarPor)
                        .addContainerGap(343, Short.MAX_VALUE))
                    .addGroup(jpInferirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisa)
                        .addContainerGap())))
        );
        jpInferirLayout.setVerticalGroup(
            jpInferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInferirLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlbPesquisarPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jpInferir, java.awt.BorderLayout.SOUTH);

        jpSuperior.setLayout(new java.awt.CardLayout());

        jlTitulo.setFont(new java.awt.Font("Calibri", 3, 28)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(33, 91, 147));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/aurelio_ico57.png"))); // NOI18N
        jlTitulo.setText("    Dicionário de termos de gestão");
        jlTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlTitulo.setFocusable(false);
        jlTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jpSuperior.add(jlTitulo, "card2");

        getContentPane().add(jpSuperior, java.awt.BorderLayout.NORTH);

        jpEsquerda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 91, 147)), "Cadastrar novo termo:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(33, 91, 147))); // NOI18N
        jpEsquerda.setToolTipText("");

        jlNumero.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlNumero.setLabelFor(jtfNumero);
        jlNumero.setText("Número:");

        jtfNumero.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroActionPerformed(evt);
            }
        });

        jlTermo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlTermo.setText("Termo:");

        jlSignificado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlSignificado.setText("Significado:");

        jlbFonte.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlbFonte.setText("Fonte:");

        jtfFonte.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfTermo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfSignificado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jbCadastrar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbCadastrar.setText("Cadastrar");
        jbCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCadastrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEsquerdaLayout = new javax.swing.GroupLayout(jpEsquerda);
        jpEsquerda.setLayout(jpEsquerdaLayout);
        jpEsquerdaLayout.setHorizontalGroup(
            jpEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEsquerdaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEsquerdaLayout.createSequentialGroup()
                        .addGroup(jpEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTermo)
                            .addComponent(jlbFonte)
                            .addComponent(jlSignificado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNumero))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpEsquerdaLayout.createSequentialGroup()
                        .addGroup(jpEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpEsquerdaLayout.createSequentialGroup()
                                .addComponent(jbLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbCadastrar))
                            .addComponent(jtfSignificado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTermo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfFonte))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpEsquerdaLayout.setVerticalGroup(
            jpEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEsquerdaLayout.createSequentialGroup()
                .addComponent(jlNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTermo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTermo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSignificado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSignificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbFonte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jpEsquerda, java.awt.BorderLayout.LINE_START);

        jpDireita.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 91, 147)), "Outras opções:", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 16), new java.awt.Color(33, 91, 147))); // NOI18N
        jpDireita.setPreferredSize(new java.awt.Dimension(150, 186));

        jbSair.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbSair.setText("Sair");
        jbSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSair.setPreferredSize(new java.awt.Dimension(100, 27));
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbSalvar.setText("Salvar edições");
        jbSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbExibir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jbExibir.setText("Exibir");
        jbExibir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExibirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDireitaLayout = new javax.swing.GroupLayout(jpDireita);
        jpDireita.setLayout(jpDireitaLayout);
        jpDireitaLayout.setHorizontalGroup(
            jpDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDireitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDireitaLayout.createSequentialGroup()
                        .addGroup(jpDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbExibir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDireitaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpDireitaLayout.setVerticalGroup(
            jpDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDireitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jpDireita, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbSairActionPerformed
    private void pesquisar(){
    ControlaDicionario controle = new ControlaDicionario();
        String pesqNumero = jtfPesquisa.getText();
        String pesqTermo = jtfPesquisa.getText();
        String pesqSignificado = jtfPesquisa.getText();
        String pesqFonte = jtfPesquisa.getText();      
        String conteudo = controle.pesquisar(pesqNumero, pesqTermo, pesqSignificado, pesqFonte);
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();          
        table.setRowCount(0);
        
        if (conteudo != null) {              
            String[] linhas = conteudo.split("\n");
            for(String dicionario: linhas){
                String dicionarioSplit[] = dicionario.split(";");
                Object rowData[] = new Object[4]; 
                rowData[0] = dicionarioSplit[0];
                rowData[1] = dicionarioSplit[1];
                rowData[2] = dicionarioSplit[2];
                rowData[3] = dicionarioSplit[3];
                table.addRow(rowData);               
            }
            TableColumnModel columnModel = jTable1.getColumnModel();
            columnModel.getColumn(0).setPreferredWidth(15);
            columnModel.getColumn(1).setPreferredWidth(100);
            columnModel.getColumn(2).setPreferredWidth(200);
            columnModel.getColumn(3).setPreferredWidth(200);  
            jtfPesquisa.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Erro, consulta vazia!");
        }
    }                                         
    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
this.pesquisar();
       
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        Termo t  = new Termo();        
        ControlaDicionario ctlDicionario = new ControlaDicionario();        
        
        if ( (jtfNumero.getText().isEmpty()) || (jtfTermo.getText().isEmpty()) || (jtfSignificado.getText().isEmpty()) || (jtfFonte.getText().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
            jtfNumero.requestFocus();
            return;
        }
        
        String numeroAdc = jtfNumero.getText();      
        String termoAdc = jtfTermo.getText();
        String signAdc = jtfSignificado.getText();
        String fonteAdc = jtfFonte.getText();
        String conteudo = ctlDicionario.confereExis(numeroAdc,termoAdc); 
        if (conteudo == "X") {
            JOptionPane.showMessageDialog(null, "Este termo já se encontra em nosso cadastro!!");
          
            jtfNumero.requestFocus();   
            return;
        }        
        
        t.setNumero(Integer.parseInt(jtfNumero.getText()));
        t.setTermo(jtfTermo.getText());
        t.setSignificado(jtfSignificado.getText());
        t.setFonte(jtfFonte.getText());

        if (ctlDicionario.salvar(t, true)) { 
            JOptionPane.showMessageDialog(null, "Registro adicionado com SUCESSO ao arquivo!");

            DefaultTableModel table = (DefaultTableModel) jTable1.getModel();   
            Object rowData[] = new Object[4]; 
            rowData[0] = jtfNumero.getText();
            rowData[1] = jtfTermo.getText();
            rowData[2] = jtfSignificado.getText();
            rowData[3] = jtfFonte.getText();
            table.addRow(rowData);   
            
            // limpa campos
            jtfNumero.setText("");
            jtfTermo.setText("");
            jtfSignificado.setText("");
            jtfFonte.setText("");

            // posiciona cursor para proxima insercao
            jtfNumero.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Erro, problemas ao SALVAR em arquivo!");
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        jtfNumero.setText("");
            jtfTermo.setText("");
            jtfSignificado.setText("");
            jtfFonte.setText("");
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
     
    	DefaultTableModel table = (DefaultTableModel) jTable1.getModel(); 
        for (int row = 0; row < table.getRowCount(); row++) {            
            Termo t = new Termo();       
            ControlaDicionario ctlDicionario = new ControlaDicionario();  

            t.setNumero(Integer.parseInt(table.getValueAt(row, 0).toString()));
            t.setTermo(table.getValueAt(row, 1).toString());
            t.setSignificado(table.getValueAt(row, 2).toString());
            t.setFonte(table.getValueAt(row, 3).toString());
            
            if (row == 0) {        
                if (!ctlDicionario.salvar(t, false)) { 
                    JOptionPane.showMessageDialog(null, "Erro, problemas ao SALVAR em arquivo!");
                }
            } else {              
                if (!ctlDicionario.salvar(t, true)) { 
                    JOptionPane.showMessageDialog(null, "Erro, problemas ao SALVAR em arquivo!");
                }                
            }
        }      

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExibirActionPerformed
   
        int row = -1;
        row = jTable1.getSelectedRow();
        if (row != -1) {
            String termo = jTable1.getValueAt(row, 1).toString();
            String signf = jTable1.getValueAt(row, 2).toString();
            String fonte = jTable1.getValueAt(row, 3).toString();
            if (termo.isEmpty() || signf.isEmpty() || fonte.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Sem dados para mostrar!");
            } else {
                jlExibeTermo.setText(termo);
                jtpSignificado.setText(signf);
                jtpFonte.setText(fonte);
                jdExibeDados.setVisible(rootPaneCheckingEnabled);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para exibir!");
        }


             
           
    }//GEN-LAST:event_jbExibirActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        if (row < 0){
            JOptionPane.showMessageDialog(null, "Nenhuma linha selecionada!");
        }else{
            int resposta = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do termo selecionado na tabela?", "Excluir cadastro", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                table.removeRow(row);
            }
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jdExibeDados.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbExibir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JDialog jdExibeDados;
    private javax.swing.JLabel jlExibeTermo;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlSignificado;
    private javax.swing.JLabel jlTermo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlbFonte;
    private javax.swing.JLabel jlbPesquisarPor;
    private javax.swing.JPanel jpCentral;
    private javax.swing.JPanel jpDireita;
    private javax.swing.JPanel jpEsquerda;
    private javax.swing.JPanel jpInferir;
    private javax.swing.JPanel jpSuperior;
    private javax.swing.JPanel jpTras;
    private javax.swing.JTextField jtfFonte;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfSignificado;
    private javax.swing.JTextField jtfTermo;
    private javax.swing.JTextPane jtpFonte;
    private javax.swing.JTextPane jtpSignificado;
    // End of variables declaration//GEN-END:variables
}
